### PR TITLE
Recent PETSc commit has renamed PetscStackCallBLAS to PetscCallBLAS

### PR DESCRIPTION
**Pull request by francesco-ballarin**
This commit https://github.com/petsc/petsc/commit/792fecdfe9134cce4d631112660ddd34f063bc17 from 5 days ago has renamed `PetscStackCallBLAS` to `PetscCallBLAS`.

* I tested this change on my local installation.
* Before merging, the firedrake's PETSc fork should be updated to current main branch (cc @ksagiyam)
* Merging this will prevent future failure on my [FEM on Colab](https://fem-on-colab.github.io/) pipeline (which has a PETSc build during the first day of the month, and a firedrake build every saturday)

### CODE REVIEW

**Comment by ksagiyam** [comment]
This commit [`bae903cb6e5fe998dd743ea97ba6d0e4e52494ec`](https://gitlab.com/petsc/petsc/-/commit/bae903cb6e5fe998dd743ea97ba6d0e4e52494ec) from a few weeks ago breaks `tests/regression/test_nullspace.py::test_near_nullspace_mixed`, so I've been trying to fix this.

**Comment by ksagiyam** [comment]
Please see https://github.com/firedrakeproject/firedrake/pull/2518.

**Comment by wence-** [comment]
I this good to merge, or does it need more coordination?

**Comment by ksagiyam** [comment]
I think it needs to happen in the following order:

1. Firedrake updates `petsc` (and `slepc`),
2. This TinyASM PR is merged,
3. Firedrake PR https://github.com/firedrakeproject/firedrake/pull/2518 is merged,

for TinyASM/Firedrake CIs both pass.

**Comment by ksagiyam** [comment]
Actually, 2 and 3 at the same time.

**Comment by ksagiyam** [comment]
Thanks, all!

**Pull request merged**
